name: Help me!
description: If you need help using the engine.
labels: [help wanted]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your problem here."
    validations:
      required: true

  - type: dropdown
    id: btarget
    attributes:
      label: "What is your build target?"
      options:
        - "Windows x64"
        - "Windows x86/x32"
        - "Linux"
        - "Mac"
        - "HTML5/Browser (Why would you use that?)"
        - "Android (Do not.)"
    validations:
      required: true

  - type: input
    id: buildsummary
    attributes:
      label: "Did you edit anything in this build? If so, mention or summarize your changes."
      placeholder: "Yes, I edited Options.hx and tried to add a new setting"
    validations:
      required: false
